In [1]:
import pandas as pd

In [2]:
data = pd.read_parquet("results.parquet")

In [3]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 308408 entries, 0 to 308407
Data columns (total 11 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   year        305807 non-null  float64
 1   type        305807 non-null  str
 2   discipline  308407 non-null  str
 3   event       308408 non-null  str
 4   as          308408 non-null  str
 5   athlete_id  308408 non-null  int64
 6   noc         308407 non-null  str
 7   team        121714 non-null  str
 8   place       283193 non-null  float64
 9   tied        308408 non-null  bool
 10  medal       44139 non-null   str
dtypes: bool(1), float64(2), int64(1), str(7)
memory usage: 46.0 MB

In [4]:
data.shape

(308408, 11)

In [5]:
data.columns

Index(['year', 'type', 'discipline', 'event', 'as', 'athlete_id', 'noc',
       'team', 'place', 'tied', 'medal'],
      dtype='str')

In [6]:
data.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN

In [7]:
data.isna().sum()

year            2601
type            2601
discipline         1
event              0
as                 0
athlete_id         0
noc                1
team          186694
place          25215
tied               0
medal         264269
dtype: int64

In [8]:
data_new = data.copy()

In [9]:
data_new.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN

In [10]:
data_new = data_new.astype({"year": "Int64"})
data_new = data_new.astype({"place":"Int64"})
data_new["type"] = data_new["type"].fillna('Unknown').astype("string")
data_new["discipline"] = data_new["discipline"].fillna("Unknown").astype("string")
data_new["team"] = data_new["team"].fillna("No_Equipo").astype("string")
data_new["medal"] = data_new["medal"].fillna("Ninguna").astype("string")    
data_new["noc"] = data_new["noc"].fillna("No_NOC").astype("string")

In [11]:
data_new.info()

<class 'pandas.DataFrame'>
RangeIndex: 308408 entries, 0 to 308407
Data columns (total 11 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   year        305807 non-null  Int64
 1   type        308408 non-null  string
 2   discipline  308408 non-null  string
 3   event       308408 non-null  str
 4   as          308408 non-null  str
 5   athlete_id  308408 non-null  int64
 6   noc         308408 non-null  string
 7   team        308408 non-null  string
 8   place       283193 non-null  Int64
 9   tied        308408 non-null  bool
 10  medal       308408 non-null  string
dtypes: Int64(2), bool(1), int64(1), str(2), string(5)
memory usage: 49.8 MB

In [12]:
data_new.isna().sum()

year           2601
type              0
discipline        0
event             0
as                0
athlete_id        0
noc               0
team              0
place         25215
tied              0
medal             0
dtype: int64

In [13]:
data_new['type'] = data_new['type'].str.strip()
data_new['discipline'] = data_new['discipline'].str.strip()
data_new['event'] = data_new['event'].str.strip()
data_new['as'] = data_new['as'].str.strip()
data_new['noc'] = data_new['noc'].str.strip()
data_new['team'] = data_new['team'].str.strip()
data_new['medal'] = data_new['medal'].str.strip()

In [14]:
data_new.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,No_Equipo,17,True,Ninguna
1,1912,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,<NA>,False,Ninguna
2,1920,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,No_Equipo,32,True,Ninguna
3,1920,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8,True,Ninguna
4,1920,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4,False,Ninguna

In [15]:
import unicodedata  

def quitar_tildes(texto):   
    if isinstance(texto, str):
        texto = unicodedata.normalize("NFKD", texto)
        return "".join(c for c in texto if not unicodedata.combining(c))
    return texto

In [16]:
cols = ["discipline", "event", "as", "team"]

for c in cols:
    data_new[c] = data_new[c].astype("string").str.strip().map(quitar_tildes)

In [17]:
data_new

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912,Summer,Tennis,"Singles, Men (Olympic)",Jean-Francois Blanchy,1,FRA,No_Equipo,17,True,Ninguna
1,1912,Summer,Tennis,"Doubles, Men (Olympic)",Jean-Francois Blanchy,1,FRA,Jean Montariol,<NA>,False,Ninguna
2,1920,Summer,Tennis,"Singles, Men (Olympic)",Jean-Francois Blanchy,1,FRA,No_Equipo,32,True,Ninguna
3,1920,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-Francois Blanchy,1,FRA,Jeanne Vaussard,8,True,Ninguna
4,1920,Summer,Tennis,"Doubles, Men (Olympic)",Jean-Francois Blanchy,1,FRA,Jacques Brugnon,4,False,Ninguna
...,...,...,...,...,...,...,...,...,...,...,...
308403,2022,Winter,Luge,"Singles, Men (Olympic)",Marian Skupek,148983,SVK,No_Equipo,26,False,Ninguna
308404,2022,Winter,Alpine Skiing (Skiing),"Slalom, Women (Olympic)",Elsa Fermback,148984,SWE,No_Equipo,28,False,Ninguna
308405,2022,Winter,Alpine Skiing (Skiing),"Team, Mixed (Olympic)",Hilma Lovblom,148985,SWE,Sweden,13,False,Ninguna
308406,2022,Winter,Alpine Skiing (Skiing),"Giant Slalom, Women (Olympic)",Hilma Lovblom,148985,SWE,No_Equipo,<NA>,False,Ninguna
308407,2022,Winter,Unknown,"Slalom, Women (Olympic)",Charlotta Safvenberg,148986,No_NOC,No_Equipo,24,False,Ninguna

In [18]:
data_new.info()

<class 'pandas.DataFrame'>
RangeIndex: 308408 entries, 0 to 308407
Data columns (total 11 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   year        305807 non-null  Int64
 1   type        308408 non-null  string
 2   discipline  308408 non-null  str
 3   event       308408 non-null  str
 4   as          308408 non-null  str
 5   athlete_id  308408 non-null  int64
 6   noc         308408 non-null  string
 7   team        308408 non-null  str
 8   place       283193 non-null  Int64
 9   tied        308408 non-null  bool
 10  medal       308408 non-null  string
dtypes: Int64(2), bool(1), int64(1), str(4), string(3)
memory usage: 49.9 MB

In [19]:
data_new = data_new.rename(columns={'year': 'Año'}) 
data_new = data_new.rename(columns={'type': 'Juegos'}) 
data_new = data_new.rename(columns={'discipline': 'Deporte'}) 
data_new = data_new.rename(columns={'event': 'Categoria'}) 
data_new = data_new.rename(columns={'as': 'Atleta'}) 
data_new = data_new.rename(columns={'athlete_id': 'ID_Atleta'}) 
data_new = data_new.rename(columns={'noc': 'NOC'}) 
data_new = data_new.rename(columns={'team': 'Equipo'}) 
data_new = data_new.rename(columns={'place': 'Posicion'}) 
data_new = data_new.rename(columns={'tied': 'Empatado'}) 
data_new = data_new.rename(columns={'medal': 'Medalla'})

In [20]:
data_new['Juegos'] = data_new['Juegos'].str.replace("Summer", "Verano", regex=False)    
data_new['Juegos'] = data_new['Juegos'].str.replace("Winter", "Invierno", regex=False)

In [21]:
data_new.head()

,Año,Juegos,Deporte,Categoria,Atleta,ID_Atleta,NOC,Equipo,Posicion,Empatado,Medalla
0,1912,Verano,Tennis,"Singles, Men (Olympic)",Jean-Francois Blanchy,1,FRA,No_Equipo,17,True,Ninguna
1,1912,Verano,Tennis,"Doubles, Men (Olympic)",Jean-Francois Blanchy,1,FRA,Jean Montariol,<NA>,False,Ninguna
2,1920,Verano,Tennis,"Singles, Men (Olympic)",Jean-Francois Blanchy,1,FRA,No_Equipo,32,True,Ninguna
3,1920,Verano,Tennis,"Doubles, Mixed (Olympic)",Jean-Francois Blanchy,1,FRA,Jeanne Vaussard,8,True,Ninguna
4,1920,Verano,Tennis,"Doubles, Men (Olympic)",Jean-Francois Blanchy,1,FRA,Jacques Brugnon,4,False,Ninguna